# -*- coding: utf-8 -*-
"""sales_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PRuC4agB-mM1AxaR2BoC6n9ghDLhBHPX

# **1**.**Create** **sales_analysis**.**py**

**#Setup** & **load** **data**
"""

import pandas as pd

"""**#Load** CSV file into a DataFrame"""

df=pd.read_csv('sales_data.csv')
print(df)

"""**#Quick** check that data loaded"""

print("First 5 rows:")
print(df.head())

"""# **2**. **Explore** **data**

**#Number** of rows and columns
"""

print("Shape of data (rows, columns):")
print(df.shape)

"""**#List** of all column names"""

print("\nColumn names:")
print(df.columns.tolist())

"""**#Data** type of each column"""

print("\nData types:")
print(df.dtypes)

"""**#Stats** for numeric and non-numeric"""

print("\nBasic summary statistics:")
print(df.describe(include="all"))

"""# **3**.**Clean** **data** (**missing** **values** & **duplicates**)

**#Drop** completely duplicated rows
"""

df = df.drop_duplicates()

"""**#Handle** missing product names: drop rows where product is missing"""

df = df.dropna(subset=["Product"])

"""**#Handle** missing quantities: fill with 0"""

df["Quantity"] = df["Quantity"].fillna(0)

"""**#Ensure** numeric types for quantity and price"""

df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce").fillna(0)
df["Price"] = pd.to_numeric(df["Price"], errors="coerce")

print("Cleaned data preview:")
print(df.head())

"""# **4**. **Analyze** **sales** (**compute** **metrics**)

**#Create** revenue column
"""

df["revenue"] = df["Quantity"] * df["Price"]

"""--- **Metrics** (**at** **least** **3**) ---

**#Total** revenue (total sales)
"""

total_revenue = df["revenue"].sum()

"""**#Total** number of orders after cleaning"""

total_orders = len(df)

"""**#Revenue** by product"""

revenue_by_product = df.groupby("Product")["revenue"].sum().sort_values(ascending=False)

"""**#Quantity** sold by product"""

quantity_by_product = df.groupby("Product")["Quantity"].sum().sort_values(ascending=False)

"""**#Best**-**selling** **product** **by** **revenue**"""

best_product_by_revenue = revenue_by_product.idxmax()
best_product_revenue = revenue_by_product.max()

print("Total revenue:", total_revenue)
print("Total orders:", total_orders)
print("\nRevenue by product:")
print(revenue_by_product)
print("\nQuantity by product:")
print(quantity_by_product)
print("\nBest product by revenue:", best_product_by_revenue, "->", best_product_revenue)